### PR TITLE
Adds rank column

### PR DESCRIPTION
**Pull request by AndreasInk**
### Adds rank column
- This doesn't add any logic, just opening the floor for a rank column that can rank whose the best professor based on ISQ and GPA data
- Open PDF was truncated so I made it simply PDF

image

### CODE REVIEW

**Comment by AndreasInk** [comment]
Just noticed when I scroll, the time value can truncate so might want to fix that

**Comment by rothso** [comment]
UI looks good! I switched it to target the `dev` branch so I can deploy it to https://dev.syllabank.com/ for live testing. Also could you run `yarn client:lint` and take care of the indentation formatting issue that it mentions for SectionDetails.tsx? Thanks!

**Comment by AndreasInk** [comment]
Thanks, sure thing I'll run the linter!

**Comment by rothso** [comment]
Also, if you're on VS Code, I have the project configured so that if you install both the Prettier and ESLint extensions you should see the lint errors live in the editor too, without having to remember to run the linter every time :smile:

**Pull request merged**
